name: marsouly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.20
  dio: ^5.3.0
  fpdart: ^0.6.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  pin_code_fields: ^7.4.0
  icons_plus: ^4.0.0
  connectivity_plus: ^3.0.3
  flutter_animation_progress_bar: ^2.3.1
  curved_progress_bar: ^1.0.2
  font_awesome_flutter: ^10.4.0
  # google_maps_flutter: ^2.2.5
  location: ^4.4.0
  flutter_keyboard_visibility: ^5.4.0
  carousel_slider: ^4.2.1
  path_provider: ^2.0.14
  shimmer: ^2.0.0
  image_picker: ^0.8.7+2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  fonts:
    - family: Marsoulna
      fonts:
        - asset: fonts/Marsoulna-Regular.ttf
          weight: 500
        - asset: fonts/Marsoulna-Bold.ttf
          weight: 700
